# Site settings
title: Madeira
client:
  name: Bloemeneiland met unieke natuur
  link: "https://www.visitportugal.com/"

core-se-link: https://www.secretescapes.de/aktuelle-angebote
description: >
  De archipel Madeira ligt midden in de Atlantische Oceaan voor de noordwestkust van Afrika. Naast het gelijknamige hoofdeiland omvat het ook Porto Santo, Ilhas Desertas en Ilhas Selvagens

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/nl/2020/madeira" # the subpath of your site, e.g. /blog/
img:     "/nl/2020/madeira/_assets/img"
css:     "/nl/2020/madeira/_assets/css"
js:      "/nl/2020/madeira/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
